<script type="text/javascript" src="./datatable/jquery-3.3.1.js"></script>
<script type="text/javascript" src="./datatable/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="./datatable/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="./datatable/dataTables.semanticui.min.js"></script>
<script type="text/javascript" src="./datatable/buttons.semanticui.min.js"></script>
<script type="text/javascript" src="./datatable/buttons.flash.min.js"></script>
<script type="text/javascript" src="./datatable/jszip.min.js"></script>
<script type="text/javascript" src="./datatable/pdfmake.min.js"></script>
<script type="text/javascript" src="./datatable/vfs_fonts.js"></script>
<script type="text/javascript" src="./datatable/buttons.html5.min.js"></script>
<script type="text/javascript" src="./datatable/buttons.print.min.js"></script>
<script type="text/javascript" src="./datatable/buttons.colVis.min.js"></script>
